all: myshell2.o myls.o mycp.o mymv.o grep.o
	gcc myshell2.o myls.o mycp.o mymv.o grep.o -lreadline

myshell2.o: myshell2.c
	gcc -c myshell2.c

myls.o: myls.c
	gcc -c myls.c

mycp.o: mycp.c
	gcc -c mycp.c

mymv.o: mymv.c 
	gcc -c mymv.c

grep.o: grep.c 
	gcc -c grep.c	


